name: sohan_flutter_template
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  intl: ^0.20.2
  connectivity_plus: ^6.1.3
  permission_handler: ^11.4.0
  logger: ^2.5.0
  dio: ^5.8.0+1
  flutter_svg: ^2.0.17
  pin_code_fields: ^8.0.1
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

#  fonts:
#    - family: KantumruyPro
#      fonts:
#        - asset: assets/fonts/KantumruyPro-Light.ttf
#          weight: 300
#        - asset: assets/fonts/KantumruyPro-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/KantumruyPro-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/KantumruyPro-SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/KantumruyPro-Bold.ttf
#          weight: 700