name: sohan_starter_temp_clean_getx
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  sohan_starter_temp_clean_getx: bin/sohan_starter_temp_clean_getx.dart



homepage: "https://github.com/Sohan-14/sohan_starter_temp_clean_getx"
repository: "https://github.com/Sohan-14/sohan_starter_temp_clean_getx"